services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: ktech
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: ktech-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 4223
            MYSQL_DATABASE: ktech
            MYSQL_USER: ktech
            MYSQL_PASSWORD: 4223
            TZ: Asia/Ho_Chi_Minh
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    dbdata:

networks:
    laravel:
