services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ktech
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kltn
      MYSQL_USER: ktech
      MYSQL_PASSWORD: 4223
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
